POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNtaXRoamVmIiwiaWQiOiI1YzZhZjEyYWI1NmI2YTVjZDc1MDQ3ZWIiLCJpYXQiOjE1NTA1MTUwMzZ9.9gNr__g2fxrV_4TQ5bIHvsCQDQorOBUbyXAbEnlCfrU

{
    "title": "Add blog with token authorization 1",
    "author": "Author 5000",
    "url": "www.testurl.com/blog5000",
    "likes": 20
}